config/routes.rb
Rails.application.routes.draw do
  root to: "home_pages#index"
  get "/update_cart", to: "carts#update"
  get "/destroy_cart", to: "carts#destroy"
  get "/show_order", to: "orders#show"
  post "/payment", to: "orders#create"

  resources :orders, only: %i(index)
  resources :carts, only: %i(create)
  resources :products, only: %i(index)
  resources :combos, only: %i(index)
  resources :stores, only: %i(show)

  resources :stores, only: :show

  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}

  scope module: "admin", path: "admin", as: "admin" do
    get "/home", to: "homes#index"
    get "/new_user", to: "users#new_user"
    get "/edit_user", to: "users#edit_user"
    get "/show_user", to: "users#show_user"

    resources :users
  end

  scope module: "manager", path: "manager", as: "manager" do
    get "/home", to: "homes#index"

    resources :combos
    resources :comments, only: %i(create destroy)
    resources :stores
    resources :products
    resources :bills
    resources :districts, only: %i(index)
  end
end

app/models/store.rb
class Store < ApplicationRecord
  STORE_PARAMS = %i(address phone district_id user_id).freeze

  belongs_to :user
  belongs_to :district
  has_many :bills, dependent: :destroy
  has_many :combos, dependent: :destroy
  has_many :products, dependent: :destroy

  delegate :name, to: :district, prefix: true

  validates :address, presence: true
  validates :phone, presence: true
  validates :district_id, presence: true

  scope :by_province_id, ->(province_id){where(districts: {province_id: province_id})}
end

app/controllers/manager/bills_controller.rb
class Manager::BillsController < ManagerController
  load_and_authorize_resource
  before_action :load_bill, only: %i(show update destroy)

  def index
    @search = Bill.ransack params[:search]
    @bills = @search.result.page(params[:page])
      .by_store_ids(store_ids)
      .per Settings.manager.bill.num_in_page
  end

  def show; end

  def update
    if @bill.update_attributes status: params[:status]
      render json: {state: :success, status: :ok, data: @bill}
    else
      render json: {state: :errors, status: :not_found, data: @bill.errors}
    end
  end

  private

  def bill_params
    params.require(:bill).permit Bill::BILL_PARAMS
  end

  def store_ids
    current_user.store_ids
  end

  def load_bill
    @bill = Bill.find_by_id params[:id]

    return if @bill
    flash[:danger] = t(".not_exits")
    redirect_to root_path
  end
end

app/controllers/manager/combos_controller.rb
class Manager::CombosController < ManagerController
  load_and_authorize_resource
  before_action :load_combo, except: %i(index new create)
  before_action :load_products, only: %i(show)
  before_action :load_parent_comments, only: %i(show)

  def index
    @search = Combo.ransack params[:search]
    @combos = @search.result.includes(:images).page(params[:page])
      .combo_of_current_user(combo_id_current_user)
      .per Settings.manager.combo.num_in_page
  end

  def show
    @comment = Comment.new
  end

  def new
    @combo = Combo.new
  end

  def edit; end

  def create
    @combo = Combo.new combo_params

    if @combo.save
      flash[:success] = t(".success")
      redirect_to manager_combos_path
    else
      render :new
    end
  end

  def update
    if @combo.update_attributes combo_params
      flash[:success] = t(".success")
      redirect_to manager_combos_path
    else
      render :new
    end
  end

  def destroy
    if @combo.destroy
      flash[:success] = t(".success")
    else
      flash[:danger] = t(".error")
    end
    redirect_to manager_combos_url
  end

  private

  def combo_id_current_user
    current_user.combos.pluck :id
  end

  def combo_params
    params.require(:combo).permit Combo::COMBO_PARAMS
  end
  
  def load_combo
    @combo = Combo.find_by_id params[:id]

    return if @combo
    flash[:danger] = t(".not_exits")
    redirect_to root_path
  end

  def load_products
    @products = @combo.products
  end

  def load_parent_comments
    @parent_comments = @combo.comments.parent_comment
  end
end

app/controllers/manager/comments_controller.rb
class Manager::CommentsController < ManagerController
  skip_load_and_authorize_resource
  before_action :load_comment, only: %i(edit update destroy)

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new comment_params
    @comment.save

    respond_to :js
  end
  
  def destroy
    @comment.destroy

    respond_to :js
  end
  
  private

  def comment_params
    params.require(:comment).permit Comment::COMMENT_PARAMS
  end
  
  def load_comment
    @comment = Comment.find_by_id params[:id]

    return if @comment
    flash[:danger] = t(".not_exits")
    redirect_to root_path
  end
end

app/controllers/manager/districts_controller.rb
class Manager::DistrictsController < ManagerController
  load_and_authorize_resource
  
  def index
    @districts = District.by_province_id params[:id]

    respond_to :js
  end
end

app/controllers/manager/homes_controller.rb
class Manager::HomesController < ManagerController
  skip_load_and_authorize_resource
  
  def index; end
end

app/controllers/manager/products_controller.rb
class Manager::ProductsController < ManagerController
  load_and_authorize_resource
  before_action :load_product, except: %i(index create new)
  before_action :load_parent_comments, only: %i(show)

  def index
    @search = Product.ransack params[:search]
    @products = @search.result.page(params[:page])
      .products_of_current_user(product_ids_current_user)
      .per Settings.manager.product.num_in_page
  end

  def new
    @product = Product.new
  end

  def edit; end

  def show
    @comment = Comment.new
  end

  def create
    @product = Product.new product_params
    
    if @product.save
      flash[:success] = t(".success")
      redirect_to manager_products_path
    else
      render :new
    end
  end

  def update
    if @product.update_attributes product_params
      flash[:success] = t(".success")
      redirect_to manager_products_path
    else
      render :new
    end
  end

  def destroy
    if @product.destroy
      flash[:success] = t(".success")
    else
      flash[:danger] = t(".error")
    end
    redirect_to manager_products_url
  end

  private

  def product_ids_current_user
    current_user.products.pluck :id
  end

  def product_params
    params.require(:product).permit Product::PRODUCT_PARAMS
  end
  
  def load_product
    @product = Product.find_by_id params[:id]

    return if @product
    flash[:danger] = t(".not_exits")
    redirect_to root_path
  end

  def load_parent_comments
    @parent_comments = @product.comments.parent_comment
  end
end

app/controllers/manager/stores_controller.rb
class Manager::StoresController < ManagerController
  load_and_authorize_resource
  before_action :load_store, only: %i(edit update destroy)

  def index
    @stores = current_user.stores

    respond_to :js
  end

  def new
    @store = Store.new

    respond_to :js
  end

  def create
    @store = Store.new store_params

    if @store.save
      render json: {success: render_to_string(partial: "manager/stores/create",
        locals: {store: @store}, layout: false)}
    else
      render json: {errors: @store.errors}
    end
  end
  
  def edit
    respond_to :js
  end

  def update
    if @store.update_attributes store_params
      render json: {success: @store}
    else
      render json: {errors: @store.errors}
    end
  end

  def destroy
    @store.destroy

    respond_to :js
  end

  def get_districts
    @districts = District.by_province_id params[:id]
    respond_to :js
  end

  private

  def store_params
    params.require(:store).permit Store::STORE_PARAMS
  end

  def load_store
    @store = Store.find_by_id params[:id]

    return if @store
    flash[:danger] = t(".not_exits")
    redirect_to root_path
  end
end

app/controllers/manager_controller.rb
class ManagerController < ActionController::Base
  load_and_authorize_resource unless: :devise_controller?
  before_action :authenticate_user!
  before_action :verify_manager

  def manager_user
    return if current_user.manager?
    flash[:danger] = t(".not_role")
    redirect_to root_url
  end

  protected

  def verify_manager
    redirect_to root_path unless current_user.manager?
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  include StoresHelper

  before_action :load_combos, only: %i(show)
  before_action :load_products, only: %i(show)

  def show; end

  private
  
  def load_combos
    @combos = Combo.by_store_id(params[:id]).take Settings.num_in_web
  end

  def load_products
    @products = Product.by_store_id(params[:id]).take Settings.num_in_web
  end
end

app/helpers/stores_helper.rb
module StoresHelper
  def get_provinces
    Province.pluck :name, :id
  end

  def get_distric_brothers store
    return if store.id.blank?
    District.by_province_id(store.district.province_id).
      pluck :name, :id
  end

  def stt_store_create
    current_user.stores.count
  end
end

app/views/manager/stores/_create.html.erb
<tr id="<%= "store-#{store.id}" %>" class="<%= "stt-#{stt_store_create}" %>">
  <td><%= stt_store_create %></td>
  <td id="phone-<%= store.id %>"><%= store.phone %></td>
  <td id="address-<%= store.id %>"><%= store.address %></td>
  <td>
    <%= link_to edit_manager_store_path(store),
      class: "btn btn-warning btn-sm", remote: true do %>
      <i class="fa fa-edit"></i>
    <% end %>
    <%= link_to manager_store_path(store), method: :delete,
      data: {confirm: t(".sure")}, remote: true,
      class: "btn btn-danger btn-sm" do %>
      <i class="fa fa-trash"></i>
    <% end %>
  </td>
</tr>

app/views/manager/stores/_edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title"><%= t ".edit_store" %></h4>
        </div>
        <div class="card-body">
          <%= render "form", {store: @store, type: :edit} %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/manager/stores/_form.html.erb
<%= form_for [:manager, @store], :html => {:multipart => true}, class: "form-group edit_store" do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <%= f.hidden_field :user_id, value: current_user.id %>

  <div class="row">
    <div class="col">
      <%= f.label t(".address") %>
      <%= f.text_field :address, class: "form-control mb-1" %>
      <div class="my_error mb-2" id="error_address_<%= type %>"></div>
    </div>
    <div class="col">
      <%= f.label t(".phone") %>
      <%= f.text_field :phone, class: "form-control mb-1" %>
      <div class="my_error mb-2" id="error_phone_<%= type %>"></div>
    </div>
  </div>
  <% if @store.persisted? %>
    <div class="row">
      <div class="col">
        <%= label_tag t(".provinces") %>
        <%= select_tag "store[province_id]", options_for_select(get_provinces),
          id: "provinces", class: "form-control mb-1 select2" %>
      </div>

      <div class="col" id="districts">
        <%= f.label t(".districts") %>
        <%= f.select :district_id, options_for_select(get_distric_brothers(@store),
          selected: @store.district_id),
          {include_blank: false}, class: "form-control select2" %>
        <div class="my_error mb-2" id="error_district_id_<%= type %>"></div>
      </div>
    </div>
  <% else %>
    <div class="row">
      <div class="col">
        <%= label_tag t(".provinces") %>
        <%= select_tag "store[province_id]", options_for_select(get_provinces),
          {prompt: t(".select"), id: "provinces", class: "form-control select2"} %>
      </div>

      <div class="col" id="districts">
        <%= f.label t(".districts") %>
        <%= f.text_field :district, class: "form-control", disabled: true %>
        <div class="my_error mb-2" id="error_district_id_<%= type %>"></div>
      </div>
    </div>
  <% end %>

  <%= button_tag class: "btn btn-primary btn-sm mt-3" do %>
    <i class="fa fa-paper-plane"></i> <%= t ".submit" %>
  <% end %>
  
  <%= button_tag type: :reset,
    class: "btn btn-warning btn-sm mr-2 mt-3" do %>
    <i class="fa fa-reply"></i> <%= t ".reset" %>
  <% end %>
<% end %>

app/views/manager/stores/_index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="cart-header">
          <% if can? :create, Store %>
            <button class="btn btn-success btn-sm m-2" id="add_store">
              <i class="fa fa-plus"></i> <%=  t ".add_store" %>
            </button>
          <% end %>
        </div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <th><%= t ".stt" %></th>
                  <th><%= t ".phone" %></th>
                  <th><%= t ".address" %></th>
                  <th></th>
                </tr>
              </thead>
              <tbody id="table_stores">
                <%= render partial: :store, collection: @stores %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/manager/stores/_new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title"><%= t ".new_store" %></h4>
        </div>
        <div class="card-body">
          <%= render "form", {store: @store, type: :new} %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/manager/stores/_store.html.erb
<tr id="<%= "store-#{store.id}" %>">
  <td><%= get_index_page store_counter %></td>
  <td id="phone-<%= store.id %>"><%= store.phone %></td>
  <td id="address-<%= store.id %>"><%= store.address %></td>
  <td>
    <% if can? :read, store %>
      <%= link_to edit_manager_store_path(store),
        class: "btn btn-warning btn-sm", remote: true do %>
        <i class="fa fa-edit"></i>
      <% end %>
    <% end %>

    <% if can? :update, store %>
      <%= link_to manager_store_path(store), method: :delete,
        data: {confirm: t(".sure")}, remote: true,
        class: "btn btn-danger btn-sm" do %>
        <i class="fa fa-trash"></i>
      <% end %>
    <% end %>
  </td>
</tr>

app/views/manager/stores/destroy.js.erb
<% if @store.destroyed? %>
  $('#store-<%= @store.id %>').remove();
  $('#message_store').addClass('alert-success d-block');
  $('#content_store').html('<%= t ".success" %>');
<% else %>
  $('#message_store').addClass('alert-danger d-block');
  $('#content_store').html('<%= t ".error" %>');
<% end %>
close_alert();

app/views/manager/stores/edit.js.erb
$('#store_form').html('<%= j render partial: "edit", store: @store %>');
$('.select2').select2({theme: 'bootstrap'});

app/views/manager/stores/get_districts.js.erb
$('#districts').html('<%= j render partial: "districts", districts: @districts %>');
$('.select2').select2({theme: 'bootstrap'});

app/views/manager/stores/index.js.erb
$('#list_store').html('<%= j render partial: "index", stores: @stores %>');
$('.select2').select2({theme: 'bootstrap'});

app/views/manager/stores/new.js.erb
$('#store_form').html('<%= j render partial: "new", store: @store %>');
$('.select2').select2({theme: 'bootstrap'});