config/routes.rb
Rails.application.routes.draw do
  root to: "home_pages#index"
  get "/update_cart", to: "carts#update"
  get "/destroy_cart", to: "carts#destroy"
  get "/show_order", to: "orders#show"
  post "/payment", to: "orders#create"

  resources :orders, only: %i(index)
  resources :carts, only: %i(create)
  resources :products, only: %i(index)
  resources :combos, only: %i(index)
  resources :stores, only: %i(show)

  resources :stores, only: :show

  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}

  scope module: "admin", path: "admin", as: "admin" do
    get "/home", to: "homes#index"
    get "/new_user", to: "users#new_user"
    get "/edit_user", to: "users#edit_user"
    get "/show_user", to: "users#show_user"

    resources :users
  end

  scope module: "manager", path: "manager", as: "manager" do
    get "/home", to: "homes#index"

    resources :combos
    resources :comments, only: %i(create destroy)
    resources :stores
    resources :products
    resources :bills
    resources :districts, only: %i(index)
  end
end

app/views/layouts/admin/_header.html.erb
<header class="topbar">
  <nav class="navbar top-navbar navbar-expand-md navbar-dark">
    <div class="navbar-header">
      <%= link_to t(".home") do %>
        <%= image_tag "logo.png" %>
      <% end %>
    </div>
    <div class="navbar-collapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item nav-right hidden-sm-up">
          <%= link_to "", class: "nav-link nav-toggler waves-effect waves-light" do %>
            <i class="ti-menu"></i>
          <% end %>
        </li>
      </ul>

      <ul class="navbar-nav my-lg-0">
        <li class="nav-item dropdown">
          <%= link_to "#", class: "nav-link dropdown-toggle text-muted waves-effect waves-dark",
"data-toggle": "dropdown", "aria-haspopup": "true", "aria-expanded": "false" do %>
            <%= image_tag "avata.png", alt: "user", class: "img-circle", width: Settings.admin.width_avata %>
          <% end %>
        </li>
      </ul>

      <ul class="navbar-nav mr-4 ml-2">
        <li>
          <%= link_to destroy_user_session_path, method: :delete,
            class: "btn btn-danger btn-sm" do %>
            <i class="fa fa-sign-out"></i> <%= t ".logout" %>
          <% end %>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/admin/_slider.html.erb
<aside class="left-sidebar">
  <div class="d-flex no-block nav-text-box align-items-center">
    <span>
      <%= image_tag "logo.png" %>
    </span>
    <%= link_to admin_home_path, class: "waves-effect waves-dark ml-auto hidden-sm-down" do %>
      <i class="ti-menu"></i>
    <% end %>
    <%= link_to root_path, class: "waves-effect waves-dark ml-auto hidden-sm-down" do %>
      <i class="fa fa-home"></i>
    <% end %>
  </div>

  <div class="scroll-sidebar">
    <nav class="sidebar-nav">
      <ul id="sidebarnav">
        <li>
          <%= link_to admin_home_path, class: "waves-effect waves-dark", "aria-expanded": "false" do %>
            <i class="fa fa-tachometer"></i>
            <span class="hide-menu"><%= t ".dashboard" %></span>
          <% end %>
        <li>
        <li>
          <%= link_to admin_users_path, class: "waves-effect waves-dark", "aria-expanded": "false" do %>
            <i class="fa fa-user"></i>
            <span class="hide-menu"><%= t ".user" %></span>
          <% end %>
        <li>
      </ul>
    </nav>
  </div>
</aside>