config/routes.rb
Rails.application.routes.draw do
  root to: "home_pages#index"
  get "/update_cart", to: "carts#update"
  get "/destroy_cart", to: "carts#destroy"
  get "/show_order", to: "orders#show"
  post "/payment", to: "orders#create"

  resources :orders, only: %i(index)
  resources :carts, only: %i(create)
  resources :products, only: %i(index)
  resources :combos, only: %i(index)
  resources :stores, only: %i(show)

  resources :stores, only: :show

  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}

  scope module: "admin", path: "admin", as: "admin" do
    get "/home", to: "homes#index"
    get "/new_user", to: "users#new_user"
    get "/edit_user", to: "users#edit_user"
    get "/show_user", to: "users#show_user"

    resources :users
  end

  scope module: "manager", path: "manager", as: "manager" do
    get "/home", to: "homes#index"

    resources :combos
    resources :comments, only: %i(create destroy)
    resources :stores
    resources :products
    resources :bills
    resources :districts, only: %i(index)
  end
end

app/models/user.rb
class User < ApplicationRecord
  USER_PARAMS = %i(phone address name email cost password password_confirmation role).freeze

  enum role: {normal: 0, manager: 1, admin: 2}
  
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable,
    :omniauthable, omniauth_providers: [:facebook]

  has_many :stores, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :bills, dependent: :destroy
  has_many :combos, through: :stores
  has_many :products, through: :stores

  validates :address, presence: true, length:
    {minimum: Settings.user.min_address_length,
    maximum: Settings.user.max_address_length}, allow_nil: true
  validates :phone, presence: true, length:
    {maximum: Settings.user.max_phone_length}, allow_nil: true
  validates :name, presence: true, length:
    {minimum: Settings.user.min_name_length,
    maximum: Settings.user.max_name_length}, allow_nil: true
  validates :cost, presence: true, numericality: {greater_than: Settings.zero}  

  scope :order_by_role, ->{order role: :desc}

  private

  def new_with_session params, session
    tap do |user|
      if data = session["devise.#facebook_data"] &&
        session["devise.facebook_data"]["extra"]["raw_info"]
        next unless user.email.blank?
        user.email = data["email"]
      end
    end
  end

  class << self
    def from_omniauth auth
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[Settings.user.min_password_length,
          Settings.user.max_password_length]
        user.name = auth.info.name
        user.image = auth.info.image
      end
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  load_and_authorize_resource
  before_action :load_user, except: %i(index create new)

  def index
    @search = User.ransack params[:search]
    @users = @search.result.order_by_role.page(params[:page]).per Settings.admin.user.num_in_page
  end

  def new
    @user = User.new

    respond_to :js
  end

  def show
    respond_to :js
  end

  def edit
    respond_to :js
  end

  def update
    if @user.update_attributes user_params
      render json: {success: @user}
    else
      render json: {errors: @user.errors}
    end
  end

  def create
    @user = User.new user_params
    
    if @user.save
      render json: {success: render_to_string(partial: "admin/users/create",
        locals: {user: @user}, layout: false)}
    else
      render json: {errors: @user.errors}
    end
  end

  def destroy
    if @user.destroy
      flash[:success] = t(".success")
    else
      flash[:danger] = t(".error")
    end
    redirect_to admin_users_url
  end

  private
  
  def user_params
    params.require(:user).permit User::USER_PARAMS
  end

  def load_user
    @user = User.find_by_id params[:id]
    
    return if @user
    flash[:danger] = t(".not_exits")
    redirect_to root_path
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    generic_callback Settings.omniauth.facebook
  end

  def generic_callback provider
    @user = User.from_omniauth request.env["omniauth.auth"]

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: provider.capitalize) if is_navigational_format?
    else
      session["devise.#{provider}_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/views/admin/users/_create.html.erb
<tr id="<%= "user-#{user.id}" %>" class="user-0">
  <td>1</td>
  <td><%= image_tag user.image if user.image? %></td>
  <td id="<%= "email-#{user.id}" %>"><%= user.email %></td>
  <td>
    <span class="label
      <%= if user.role.eql? "admin"
        "label-danger"
      elsif user.role.eql? "manager"
        "label-warning"
      else
        "label-info"
      end %> ">
      <%= enum_l user, :role %>
    </span>
  </td>
  <td>
    <button class="btn btn-info btn-sm" onclick="show_user('<%= user.id %>');"
      data-toggle="modal" data-target="#form_show">
      <i class="fa fa-eye"></i>
    </button>

    <button class="btn btn-warning btn-sm" onclick="edit_user('<%= user.id %>');"
      data-toggle="modal" data-target="#form_edit">
      <i class="fa fa-edit"></i>
    </button>
    <% unless user.admin? %>
      <%= link_to admin_user_path(user), method: :delete, data: {confirm: t(".sure")}, class: "btn btn-danger btn-sm" do %>
        <i class="fa fa-trash"></i>
      <% end %>
    <% end %>
  </td>
</tr>

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user], class: "form-group" do |f| %>
  <%= f.hidden_field(:role, value: Settings.user.role.enum_manager) if @user %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="row">
    <div class="col">
      <%= f.label t(".name") %>
      <%= f.text_field :name, class: "form-control mb-1" %>
      <div class="my_error mb-2" id="error_name_<%= type %>"></div>
    </div>
    <div class="col">
      <%= f.label t(".address") %>
      <%= f.text_field :address, class: "form-control mb-1" %>
      <div class="my_error mb-2" id="error_address_<%= type %>"></div>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <%= f.label t(".phone") %>
      <%= f.text_field :phone, class: "form-control mb-1" %>
      <div class="my_error mb-2" id="error_phone_<%= type %>"></div>
    </div>
    <div class="col">
      <%= f.label t(".email") %>
      <%= f.text_field :email, class: "form-control mb-1" %>
      <div class="my_error mb-2" id="error_email_<%= type %>"></div>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <%= f.label t(".cost") %>
      <%= f.text_field :cost, class: "form-control mb-1", data: {autonumeric: true} %>
      <div class="my_error mb-2" id="error_cost_<%= type %>"></div>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <%= f.label t(".password") %>
      <%= f.password_field :password, class: "form-control mb-1" %>
      <div class="my_error mb-2" id="error_password_<%= type %>"></div>
    </div>
    <div class="col">
      <%= f.label t(".password_confirmation"), t(".password_confirmation") %>
      <%= f.password_field :password_confirmation, class: "form-control mb-1" %>
      <div class="my_error mb-2" id="error_password_confirmation_<%= type %>"></div>
    </div>
  </div>

  <%= button_tag type: :submit, class: "btn btn-primary btn-sm mt-3" do %>
    <i class="fa fa-paper-plane"></i> <%= t ".submit" %>
  <% end %>
  <%= button_tag type: :reset,
    class: "btn btn-warning btn-sm mr-2 mt-3" do %>
    <i class="fa fa-reply"></i> <%= t ".reset" %>
  <% end %>
  </div>
<% end %>

app/views/admin/users/_search.html.erb
<div class="cart-body">
  <%= search_form_for [:admin, @search] do |f| %>
    <div class="row">
      <div class="col-4">
        <div class="form-group">
          <%= f.label t(".name") %>
          <%= f.search_field :name_cont, class: "form-control form-control-line" %>
        </div>
      </div>
      <div class="col-4">
        <div class="form-group">
          <%= f.label t(".email") %>
          <%= f.search_field :email_cont, class: "form-control form-control-line" %>
        </div>
      </div>
      <div class="col-4">
        <div class="form-group">
          <div id="role">
          <%= f.label t(".role") %>
          <%= f.select :role_eq,
            options_for_select(enum_options_for_select_value(User, :role),
            selected: f.object.role_eq), {include_blank: t(".search")},
            {class: "form-control select2"} %>
          </div>
        </div>
      </div>
      <div class="col">
        <%= button_tag type: :submit, class: "btn btn-success btn-sm mb-2 pt-0" do %>
          <i class="fa fa-search"></i> <%= t ".search" %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/users/_show.html.erb
<div class="card-body">
  <center class="m-t-30">
  <%= image_tag(user.image, width: Settings.admin.user.width_avata, class: "img-circle") if user.image? %>
    <h4 class="card-title m-t-10"><%= user.name %></h4>
    <h6 class="card-subtitle m-t-10"><%= user.email %></h6>
    <h6 class="card-subtitle m-t-10"><%= user.address %></h6>
    <h6 class="card-subtitle m-t-10"><%= user.phone %></h6>
    <h6 class="card-subtitle m-t-10"><%= enum_l user, :role %></h6>
  </center>
</div>

app/views/admin/users/_user.html.erb
<tr id="<%= "user-#{user.id}" %>" class="<%= "stt-#{user_counter}" %>">
  <td><%= get_index_page user_counter %></td>
  <td><%= image_tag user.image if user.image? %></td>
  <td id="<%= "email-#{user.id}" %>"><%= user.email %></td>
  <td>
    <span class="label <%= "label-#{Settings.user.role.send(user.role)}" %>">
      <%= enum_l user, :role %>
    </span>
  </td>
  <td>
    <% if can? :read, user %>
      <button class="btn btn-info btn-sm" onclick="show_user('<%= user.id %>');"
        data-toggle="modal" data-target="#form_show">
        <i class="fa fa-eye"></i>
      </button>
    <% end %>
    
    <% if can? :update, user %>
      <button class="btn btn-warning btn-sm" onclick="edit_user('<%= user.id %>', '<%= user_counter %>');"
        data-toggle="modal" data-target="#form_edit">
        <i class="fa fa-edit"></i>
      </button>
    <% end %>

    <% if can? :destroy, user %>
      <%= link_to admin_user_path(user), method: :delete, data: {confirm: t(".sure")}, class: "btn btn-danger btn-sm" do %>
        <i class="fa fa-trash"></i>
      <% end %>
    <% end %>
  </td>
</tr>

app/views/admin/users/edit.js.erb
$('#show_edit_user').html('<%= j render "form", {user: @user, type: :edit} %>');

app/views/admin/users/edit_user.js.erb
$('#show_edit_user').html('<%= j render "form", {user: @user, type: :edit} %>');

app/views/admin/users/index.html.erb
<div class="container-fluid">
  <div class="row page-titles">
    <div class="col-md-5 align-self-center">
      <% if can? :create, User %>
        <button class="btn btn-sm btn-success" id="form_new_user"
          data-toggle="modal" data-target="#form_new">
          <i class="fa fa-plus"></i>
          <%=  t ".new_user" %>
        </button>
      <% end %>
    </div>
    <div class="col-md-7 align-self-center text-right">
      <div class="d-flex justify-content-end align-items-center">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><%= link_to t(".home"), admin_home_path %></li>
          <li class="breadcrumb-item active"><i class="fa fa-plus"></i> <%= t ".new_user" %></li>
        </ol>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title"><%= t ".new_user" %></h4>
          <div class="border-search">
            <%= render partial: "search", search: @search %>
          </div>
          <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <th><%= t ".stt" %></th>
                  <th><%= t ".avata" %></th>
                  <th><%= t ".email" %></th>
                  <th><%= t ".role" %></th>
                  <th></th>
                </tr>
              </thead>
              <tbody id="table_users">
                <%= render partial: :user, collection: @users %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= paginate @users, theme: Settings.theme.theme_config %>
</div>

<div class="modal fade" id="form_new" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><%= t ".new_user" %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="show_new_user">
      </div>
      <div class="modal-footer">
        <button type="button" class="close_user btn btn-secondary" data-dismiss="modal"><%= t ".close" %></button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="form_edit" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><%= t ".edit_user" %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="show_edit_user">
      </div>
      <div class="modal-footer">
        <button type="button" class="close_user btn btn-secondary" data-dismiss="modal"><%= t ".close" %></button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="form_show" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><%= t ".show_user" %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="show_show_user">
      </div>
      <div class="modal-footer">
        <button type="button" class="close_user btn btn-secondary" data-dismiss="modal"><%= t ".close" %></button>
      </div>
    </div>
  </div>
</div>

<%= javascript_include_tag Settings.url_select2 %>

app/views/admin/users/new.js.erb
$('#show_new_user').html('<%= j render "form", {user: @user, type: :new} %>');

app/views/admin/users/new_user.js.erb
$('#show_new_user').html('<%= j render "form", {user: @user, type: :new} %>');

app/views/admin/users/show.js.erb
$('#show_show_user').html('<%= j render "show", user: @user %>');

app/views/admin/users/show_user.js.erb
$('#show_show_user').html('<%= j render "show", user: @user %>');