config/routes.rb
Rails.application.routes.draw do
  root to: "home_pages#index"
  get "/update_cart", to: "carts#update"
  get "/destroy_cart", to: "carts#destroy"
  get "/show_order", to: "orders#show"
  post "/payment", to: "orders#create"

  resources :orders, only: %i(index)
  resources :carts, only: %i(create)
  resources :products, only: %i(index)
  resources :combos, only: %i(index)
  resources :stores, only: %i(show)

  resources :stores, only: :show

  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}

  scope module: "admin", path: "admin", as: "admin" do
    get "/home", to: "homes#index"
    get "/new_user", to: "users#new_user"
    get "/edit_user", to: "users#edit_user"
    get "/show_user", to: "users#show_user"

    resources :users
  end

  scope module: "manager", path: "manager", as: "manager" do
    get "/home", to: "homes#index"

    resources :combos
    resources :comments, only: %i(create destroy)
    resources :stores
    resources :products
    resources :bills
    resources :districts, only: %i(index)
  end
end

app/models/combo.rb
class Combo < ApplicationRecord
  COMBO_PARAMS = [:name, :price, :store_id, :status, combo_products_attributes:
    [:id, :combo_id, :product_id, :count, :_destroy], images_attributes:
    [:id, :url, :alt, :image_type, :_destroy]].freeze

  enum status: {in_active: 0, active: 1}

  belongs_to :store
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :bill_details, as: :bill_detailable, dependent: :destroy
  has_many :combo_products, dependent: :destroy
  has_many :images, as: :imageable
  has_many :products, through: :combo_products

  validates :name, presence: true, length:
    {minimum: Settings.combo.min_name_length, maximum: Settings.combo.max_name_length}
  validates :price, presence: true
  validates :store_id, presence: true

  accepts_nested_attributes_for :combo_products, reject_if: :all_blank,
    allow_destroy: true
  accepts_nested_attributes_for :images, reject_if: :all_blank,
    allow_destroy: true

  scope :combo_of_current_user, ->(combo_ids){where id: combo_ids}
  scope :by_store_id, ->(store_id){where store_id: store_id}
  scope :by_combo_ids, ->(combo_ids){where id: combo_ids}
end

app/controllers/combos_controller.rb
class CombosController < ApplicationController
  before_action :load_combos, only: %i(index)

  def index
    respond_to :js
  end

  private

  def load_combos
    limit = Settings.num_in_web
    offset = Settings.num_in_web * (params[:page].to_i + Settings.zero)
    @combos = Combo.by_store_id(params[:store_id]).limit(limit).offset offset
  end
end

app/controllers/manager/bills_controller.rb
class Manager::BillsController < ManagerController
  load_and_authorize_resource
  before_action :load_bill, only: %i(show update destroy)

  def index
    @search = Bill.ransack params[:search]
    @bills = @search.result.page(params[:page])
      .by_store_ids(store_ids)
      .per Settings.manager.bill.num_in_page
  end

  def show; end

  def update
    if @bill.update_attributes status: params[:status]
      render json: {state: :success, status: :ok, data: @bill}
    else
      render json: {state: :errors, status: :not_found, data: @bill.errors}
    end
  end

  private

  def bill_params
    params.require(:bill).permit Bill::BILL_PARAMS
  end

  def store_ids
    current_user.store_ids
  end

  def load_bill
    @bill = Bill.find_by_id params[:id]

    return if @bill
    flash[:danger] = t(".not_exits")
    redirect_to root_path
  end
end

app/controllers/manager/combos_controller.rb
class Manager::CombosController < ManagerController
  load_and_authorize_resource
  before_action :load_combo, except: %i(index new create)
  before_action :load_products, only: %i(show)
  before_action :load_parent_comments, only: %i(show)

  def index
    @search = Combo.ransack params[:search]
    @combos = @search.result.includes(:images).page(params[:page])
      .combo_of_current_user(combo_id_current_user)
      .per Settings.manager.combo.num_in_page
  end

  def show
    @comment = Comment.new
  end

  def new
    @combo = Combo.new
  end

  def edit; end

  def create
    @combo = Combo.new combo_params

    if @combo.save
      flash[:success] = t(".success")
      redirect_to manager_combos_path
    else
      render :new
    end
  end

  def update
    if @combo.update_attributes combo_params
      flash[:success] = t(".success")
      redirect_to manager_combos_path
    else
      render :new
    end
  end

  def destroy
    if @combo.destroy
      flash[:success] = t(".success")
    else
      flash[:danger] = t(".error")
    end
    redirect_to manager_combos_url
  end

  private

  def combo_id_current_user
    current_user.combos.pluck :id
  end

  def combo_params
    params.require(:combo).permit Combo::COMBO_PARAMS
  end
  
  def load_combo
    @combo = Combo.find_by_id params[:id]

    return if @combo
    flash[:danger] = t(".not_exits")
    redirect_to root_path
  end

  def load_products
    @products = @combo.products
  end

  def load_parent_comments
    @parent_comments = @combo.comments.parent_comment
  end
end

app/controllers/manager/comments_controller.rb
class Manager::CommentsController < ManagerController
  skip_load_and_authorize_resource
  before_action :load_comment, only: %i(edit update destroy)

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new comment_params
    @comment.save

    respond_to :js
  end
  
  def destroy
    @comment.destroy

    respond_to :js
  end
  
  private

  def comment_params
    params.require(:comment).permit Comment::COMMENT_PARAMS
  end
  
  def load_comment
    @comment = Comment.find_by_id params[:id]

    return if @comment
    flash[:danger] = t(".not_exits")
    redirect_to root_path
  end
end

app/controllers/manager/districts_controller.rb
class Manager::DistrictsController < ManagerController
  load_and_authorize_resource
  
  def index
    @districts = District.by_province_id params[:id]

    respond_to :js
  end
end

app/controllers/manager/homes_controller.rb
class Manager::HomesController < ManagerController
  skip_load_and_authorize_resource
  
  def index; end
end

app/controllers/manager/products_controller.rb
class Manager::ProductsController < ManagerController
  load_and_authorize_resource
  before_action :load_product, except: %i(index create new)
  before_action :load_parent_comments, only: %i(show)

  def index
    @search = Product.ransack params[:search]
    @products = @search.result.page(params[:page])
      .products_of_current_user(product_ids_current_user)
      .per Settings.manager.product.num_in_page
  end

  def new
    @product = Product.new
  end

  def edit; end

  def show
    @comment = Comment.new
  end

  def create
    @product = Product.new product_params
    
    if @product.save
      flash[:success] = t(".success")
      redirect_to manager_products_path
    else
      render :new
    end
  end

  def update
    if @product.update_attributes product_params
      flash[:success] = t(".success")
      redirect_to manager_products_path
    else
      render :new
    end
  end

  def destroy
    if @product.destroy
      flash[:success] = t(".success")
    else
      flash[:danger] = t(".error")
    end
    redirect_to manager_products_url
  end

  private

  def product_ids_current_user
    current_user.products.pluck :id
  end

  def product_params
    params.require(:product).permit Product::PRODUCT_PARAMS
  end
  
  def load_product
    @product = Product.find_by_id params[:id]

    return if @product
    flash[:danger] = t(".not_exits")
    redirect_to root_path
  end

  def load_parent_comments
    @parent_comments = @product.comments.parent_comment
  end
end

app/controllers/manager/stores_controller.rb
class Manager::StoresController < ManagerController
  load_and_authorize_resource
  before_action :load_store, only: %i(edit update destroy)

  def index
    @stores = current_user.stores

    respond_to :js
  end

  def new
    @store = Store.new

    respond_to :js
  end

  def create
    @store = Store.new store_params

    if @store.save
      render json: {success: render_to_string(partial: "manager/stores/create",
        locals: {store: @store}, layout: false)}
    else
      render json: {errors: @store.errors}
    end
  end
  
  def edit
    respond_to :js
  end

  def update
    if @store.update_attributes store_params
      render json: {success: @store}
    else
      render json: {errors: @store.errors}
    end
  end

  def destroy
    @store.destroy

    respond_to :js
  end

  def get_districts
    @districts = District.by_province_id params[:id]
    respond_to :js
  end

  private

  def store_params
    params.require(:store).permit Store::STORE_PARAMS
  end

  def load_store
    @store = Store.find_by_id params[:id]

    return if @store
    flash[:danger] = t(".not_exits")
    redirect_to root_path
  end
end

app/controllers/manager_controller.rb
class ManagerController < ActionController::Base
  load_and_authorize_resource unless: :devise_controller?
  before_action :authenticate_user!
  before_action :verify_manager

  def manager_user
    return if current_user.manager?
    flash[:danger] = t(".not_role")
    redirect_to root_url
  end

  protected

  def verify_manager
    redirect_to root_path unless current_user.manager?
  end
end

app/helpers/combos_helper.rb
module CombosHelper
  def get_combos
    current_user.stores.pluck :name, :id
  end

  def get_products
    current_user.products.pluck :name, :id
  end

  def get_count_in_combo_product combo_id, product_id
    ComboProduct.get_combo_product_by_combo_id_product_id(combo_id, product_id).count
  end
end

app/views/manager/combos/_combo.html.erb
<tr id="<%= "combo-#{combo.id}" %>" class="<%= "stt-#{combo_counter}" %>">
  <td><%= get_index_page combo_counter %></td>
  <td><%= image_tag get_thumnail(combo) %></td>
  <td><%= combo.name %></td>
  <td><%= number_to_vnd combo.price %></td>
  <td><%= combo.status %></td>
  <td>
    <% if can? :read, combo %>
      <%= link_to manager_combo_path(combo), class: "btn btn-info btn-sm" do %>
        <i class="fa fa-eye"></i>
      <% end %>
    <% end %>

    <% if can? :update, combo %>
      <%= link_to edit_manager_combo_path(combo), class: "btn btn-warning btn-sm" do %>
        <i class="fa fa-edit"></i>
      <% end %>
    <% end %>

    <% if can? :destroy, combo %>
      <%= link_to manager_combo_path(combo), method: :delete, data: {confirm: t(".sure")},
        class: "btn btn-danger btn-sm" do %>
        <i class="fa fa-trash"></i>
      <% end %>
    <% end %>
  </td>
</tr>

app/views/manager/combos/_combo_product_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <div class="row">
      <div class="col-6">
        <%= f.select :product_id,
          options_for_select(get_products, selected: f.object.product_id),
          {include_blank: false},
          {class: "form-control select2"} %>
      </div>
      <div class="col-4">
        <%= f.number_field :count, class: "form-control" %>
      </div>
      <div class="col-2">
        <%= link_to_remove_association f,
          class: "btn btn-danger btn-sm" do %>
           <i class="fa fa-trash"></i> <% t ".delete_product" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= javascript_include_tag Settings.url_select2 %>

app/views/manager/combos/_comment.html.erb
<tr id="comment-<%= comment.id %>">
  <th><%= comment_counter + Settings.step %></th>
  <th><%= comment.user.name %></th>
  <th><%= l comment.created_at, format: :date_month_year %></th>
  <th class="w-50" id="sub-comment">
    <div class="card">
      <div class="card-body">
        <ul class="comment" id="reply_comment_<%= comment.id %>">
          <li id="comment-<%= comment.id %>">
          <div class="comment-show">
            <h4><i class="fa fa-comment"></i> <%= comment.content %></h4>
          </div>
          <span class="time">
            <%= l comment.created_at, format: :date_month_year %>
          </span>
          <hr>
        <li>
          <% get_sub_comment(comment).each do |sub_comment| %>  
            <li class="w-40" id="comment-<%= sub_comment.id %>">
              <div class="comment-show">
                <h6><i class="fa fa-reply-all"></i> <%= sub_comment.content %></h6>
                <span>
                  <%= link_to [:manager, sub_comment], method: :delete,
                    data: {confirm: t(".sure")}, remote: true do %>
                    <i class="fa fa-trash"></i>
                  <% end %>
                </span>
              </div>
              <span class="time">
                <%= l sub_comment.created_at, format: :date_month_year %>
              </span>
              <hr>
            <li>
          <% end %>
        </ul>
      </div>
    </div>
  </th>
  <th>
    <%= render "form_reply", comment: comment %>
  </th>
  <th>
    <%= link_to [:manager, comment], method: :delete, class: "btn btn-danger btn-sm",
      data: {confirm: t(".sure")}, remote: true do %>
      <i class="fa fa-trash"></i>
    <% end %>
  </th>
</tr>

app/views/manager/combos/_form.html.erb
<%= form_for [:manager, @combo], class: "form-group" do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="row">
    <div class="col">
      <%= f.label t(".name") %>
      <%= f.text_field :name, class: "form-control mb-1" %>
      <div class="my_error">
        <% @combo.errors[:name].each do |error| %>
          <p><%= error %></p>
        <% end %>
      </div>
    </div>
    <div class="col">
      <%= f.label t(".price") %>
      <%= f.text_field :price, data: {autonumeric: true}, class: "form-control mb-1" %>
      <div class="my_error">
        <% @combo.errors[:price].each do |error| %>
          <p><%= error %></p>
        <% end %>
      </div>
    </div>
    <div class="col">
      <%= f.label t(".store") %>
      <%= f.select :store_id, options_for_select(get_stores,
        selected: f.object.store_id),
        {include_blank: false}, {class: "select2 form-control"} %>
      <div class="my_error">
        <% @combo.errors[:store_id].each do |error| %>
          <p><%= error %></p>
        <% end %>
      </div>
    </div>
    <div class="col-2">
      <%= f.label t(".status") %>
      <%= f.select :status,
        options_for_select(enum_options_for_select(Combo, :status),
        selected: f.object.status), {include_blank: false},
        {class: "form-control select2"} %>
    </div>
  </div>
  <div id="tasks">
    <%= f.fields_for :images do |image| %>
      <%= render "image_fields", {f: image} %>
    <% end %>
    <div class="links">
      <%= link_to_add_association f, :images,
        class: "btn btn-success btn-sm mt-3" do %>
        <i class="fa fa-plus"></i> <%= t ".add_image" %>
      <% end %>
    </div>
  </div><hr>

  <div>
    <strong><%= t ".list_product" %></strong>
  </div>

  <div id="tasks"><hr>
    <div class="row">
      <div class="col-6">
        <%= t ".name_product" %>
      </div>
      <div class="col-4">
        <%= t ".count_product" %>
      </div>
    </div>

    <%= f.fields_for :combo_products do |combo_product| %>
      <%= render "combo_product_fields", {f: combo_product} %>
    <% end %>
    <div class="links">
      <%= link_to_add_association f, :combo_products,
        class: "btn btn-success btn-sm mt-3" do %>
        <i class="fa fa-plus"></i> <%= t ".add_product" %>
      <% end %>
      <%= button_tag type: :submit, class: "btn btn-primary btn-sm mt-3",
        data: {disable_with: false} do %>
        <i class="fa fa-paper-plane"></i> <%= t ".submit" %>
      <% end %>
      <%= button_tag type: :reset,
        class: "btn btn-warning btn-sm mr-2 mt-3" do %>
        <i class="fa fa-reply"></i> <%= t ".reset" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/manager/combos/_form_reply.html.erb
<%= form_for [:manager, @comment],
  class: "form-group", remote: true do |f| %>
  <%= f.text_area :content, class: "form-control", id: "content_comment" %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :parent_comment_id, value: @comment.id %>
  <%= f.hidden_field :commentable_type, value: Combo.name %>
  <%= f.hidden_field :commentable_id, value: @combo.id %>
  <%= button_tag type: :submit, class: "btn btn-success btn-sm" do %>
    <i class="fa fa-reply-all"></i>
  <% end %>
  <%= link_to [:manager, @comment], method: :delete, class: "btn btn-danger btn-sm",
    data: {confirm: t(".sure")}, remote: true do %>
    <i class="fa fa-trash"></i>
  <% end %>
<% end %>

app/views/manager/combos/_product.html.erb
<tr>
  <th><%= product_counter + Settings.step %></th>
  <th><%= link_to product.name, "#" %></th>
  <th><%= get_count_in_combo_product @combo.id, product.id %></th>
  <th><%= number_to_vnd product.price %></th>
</tr>

app/views/manager/combos/_search.html.erb
<div class="cart-body">
  <%= search_form_for [:manager, @search] do |f| %>
    <div class="row">
      <div class="col-3">
        <div class="form-group">
          <%= f.label t(".name") %>
          <%= f.search_field :name_cont, class: "form-control form-control-line" %>
        </div>
      </div>
      <div class="col-3">
        <div class="form-group">
          <%= f.label t(".store") %>
          <%= f.select :store_id_eq, options_for_select(get_stores,
            selected: f.object.store_id_eq),
            {include_blank: t(".search")}, {class: "form-control select2"} %>
        </div>
      </div>
      <div class="col-2">
        <div class="form-group">
          <%= f.label t(".price_from") %> (<%= Settings.unit %>)
          <input id="price_from_combo" name="price_from_combo" value="<%= params[:price_from_combo] %>" type="text"
            class="form-control form-control-line currencyInput validate">
          <%= f.search_field :price_gteq, class: "d-none form-control form-control-line currencyInput validate" %>
        </div>
      </div>
      <div class="col-2">
        <div class="form-group">
          <%= f.label t(".price_to") %> (<%= Settings.unit %>)
          <input id="price_to_combo" name="price_to_combo" value="<%= params[:price_to_combo] %>" type="text"
            class="form-control form-control-line currencyInput validate">
          <%= f.search_field :price_lteq, class: "d-none form-control form-control-line" %>
        </div>
      </div>
      <div class="col-2">
        <div class="form-group">
          <%= f.label t(".status") %>
          <%= f.select :status_eq,
            options_for_select(enum_options_for_select_value(Combo, :status),
            selected: f.object.status_eq),
            {include_blank: t(".search")}, {class: "form-control select2"} %>
        </div>
      </div>
      <div class="col-12">
        <%= button_tag class: "btn btn-success btn-sm mb-2 pt-0" do %>
          <i class="fa fa-search"></i> <%= t ".search" %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<%= javascript_include_tag Settings.url_format_combo %>

app/views/manager/combos/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title"><%= t ".edit_combo" %></h4>
        </div>
        <div class="card-body">
          <%= render "form" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/manager/combos/index.html.erb
<div class="container-fluid">
  <div class="row page-titles">
    <div class="col-md-5 align-self-center">
      <% if can? :create, Combo %>
        <%= link_to new_manager_combo_path, class: "btn btn-sm btn-success" do %>
        <i class="fa fa-plus"></i> <%= t ".new_combo" %>
        <% end %>
      <% end %>
    </div>
    <div class="col-md-7 align-self-center text-right">
      <div class="d-flex justify-content-end align-items-center">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><%= link_to t(".home"), manager_home_path %></li>
          <li class="breadcrumb-item active"><i class="fa fa-plus"></i> <%= t ".new_combo" %></li>
        </ol>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title"><%= t ".new_combo" %></h4>
          <div class="border-search">
            <%= render partial: "search", search: @search %>
          </div>
          <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <th><%= t ".stt" %></th>
                  <th><%= t ".thumbnail" %></th>
                  <th><%= t ".name" %></th>
                  <th><%= t ".price" %></th>
                  <th><%= t ".status" %></th>
                  <th></th>
                </tr>
              </thead>
              <tbody id="table_combos">
                <%= render @combos %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= paginate @combos, theme: Settings.theme.theme_config %>
</div>

app/views/manager/combos/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title"><%= t ".new_combo" %></h4>
        </div>
        <div class="card-body">
          <%= render "form" %>
        </div>
      </div>
    </div>
  </div>
</div>

<script src="<%= Settings.url_select2 %>"></script>

app/views/manager/combos/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <h3><%= @combo.name %></h3>
          <p><%= number_to_vnd @combo.price %></p>
          <%= enum_l @combo, :status %><br>
        </div>
      </div>
    </div>
    <% if count_thumbnails(@combo) > Settings.zero %>
      <div class="col-3">
        <strong><%= t ".thumbnails" %></strong>
        <%= render "image_show", images: get_thumbnails(@combo), id: "image-1" %>
      </div>
    <% end %>
    <% if count_images(@combo) > Settings.zero %>
      <div class="col-3">
        <strong><%= t ".images" %></strong>
        <%= render "image_show", images: get_images(@combo), id: "image-2" %>
      </div>
    <% end %>
  </div>

  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title"><%= t ".product_of_combo" %></h4>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th><%= t ".stt" %></th>
                  <th><%= t ".name" %></th>
                  <th><%= t ".count" %></th>
                  <th><%= t ".price" %></th>
                </tr>
              </thead>
              <tbody id="table_combos">
                <%= render partial: "product", collection: @products %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

  <% if @parent_comments.present? %>
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-body">
            <h4 class="card-title"><%= t ".comment" %></h4>
            <div class="table-responsive">
              <table class="table table-striped">
                <thead>
                  <tr>
                    <th><%= t ".stt" %></th>
                    <th><%= t ".comment_by" %></th>
                    <th><%= t ".created_at" %></th>
                    <th class="w-50" ><%= t ".content_and_reply" %></th>
                    <th><%= t ".reply" %></th>
                    <th></th>
                  </tr>
                </thead>
                <tbody id="table_comments">
                  <%= render partial: "comment", collection: @parent_comments %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>